# Title attributes for SVGs, for accessibility
bones-co:
  title: Bones Co.
flywheel:
  title: Flywheel
logo:
  title: BarCamp
lyconic:
  title: Lyconic
nebraskajs:
  title: NebraskaJS
object-partners:
  title: Object Partners
water-bear-games:
  title: Water Bear Games
