backend:
  name: github
  repo: aiganebraska/barcamp
  branch: master
media_folder: "images/uploads"
collections:
  - name: "sponsors" # Used in routes, e.g., /admin/collections/blog
    label: "Sponsors" # Used in the UI
    folder: "_sponsors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Link (URL)", name: "link", widget: "string"}
      - {label: "Sponsor Group", name: "group", widget: "string", default: "Bronze"}
      - {label: "Logo", name: "logo", widget: "image"}